
export const CREATE_INVITE = 'CREATE_INVITE';
export const DELETE_INVITE = 'CREATE_INVITE';

export const FETCH_INVITES_REQUEST = 'FETCH_INVITES_REQUEST';
export const FETCH_INVITES_SUCCESS = 'FETCH_INVITES_SUCCESS';
export const FETCH_INVITES_FAILURE = 'FETCH_INVITES_FAILURE';

